import { Grid, Typography } from '@mui/material';
import React from 'react';

const Privacypolicy = () => {
    return (
        <Grid container spacing={2}>
            <Grid item xs={1}></Grid>
            <Grid item xs={10}>
                <h1 style={{ textAlign: "center" }}>Privacy&Policy</h1>
                <h1 style={{ textAlign: "center", color: "#ff695f", opacity: "0.15" }}>PRIVACY</h1>
                <Typography variant='h3'>Overview</Typography>
                <br /><br />
                <Typography variant='h4' sx={{ color: "#03a4ed" }}>Herr Enterprises respect your privacy.</Typography>
                <p>Herr Enterprises is associated with offering support to its clients for promoting and marketing the B2B products by generating effective leads from the target markets.</p>
                <p>It is Herr Enterprise's policy to respect your privacy regarding any information we may collect through registration forms, resource libraries, advertising units, widgets, web sites and web pages, whether accessed via computer, mobile or tablet device, or other technology (collectively, the "Service"), collection and licensing of data through third parties we work with, and how such information may be used and/or shared with others, how we safeguard it, and your choices in controlling its use in connection with our marketing activities.</p>
                <p>This privacy policy applies when you use our services.</p>
                <p>Herr Enterprises is 100% Can-Spam Compliant</p>
                <p>Herr Enterprises has a zero-tolerance spam policy. Any partner or publisher found to be using Herr Enterprise's promotional offers for spam will be immediately cut-off from use of the product. If you know of or suspect any violators, please notify us immediately at info@herr-enterprises.com
                </p>
                <Typography variant='h4' sx={{ color: "#03a4ed" }}>Data Controller and Data Processor.</Typography>
                <p>We process two main types of personal data.</p>
                <h2><b>
                    Customer Data :</b></h2>
                <p>Personal data that forms part of data that is provided by our customers</p>
                <p>Personal data that we collect / we engage third parties to collect on behalf of our customers using campaign information provided by the customer</p>
                <p>Personal data that we purchase from third parties based on customer mandated criterion
                </p>
                <h2><b>Other Data:</b></h2>
                <p>Personal data about our customers, service providers, visitors and other individuals that is collected and processed directly by us.
                </p>
                <p>Our Customers are the controller of Customer Data. Herr Enterprises is the processor of Customer Data and the controller of Other Data.</p>
                <Typography variant='h4' sx={{ color: "#03a4ed" }}>Data Collection.</Typography>
                <h2><b>Customer Data</b></h2>
                <p>Herr Enterprises collects this data based on our customer's instructions (also known as campaign information) through different channels including business partners (publishers) using relevant technology in web marketing, E mail marketing and Telemarketing.</p>
                <p>The leads generated by the publishers are intelligently filtered to improve their quality and converted into actionable marketing targets before being passed on to the customers.
                </p>
                <p>This data includes business contact information to match criterion provided by the customer.</p>
                <h2><b>Other Data</b></h2>
                <p>We also collect data when you use our applications and websites</p>
                <h2><b>Log Data</b></h2>
                <p>Our servers automatically collect information when you access or use our applications and services. This data is recorded in log files. Examples of such data include IP Address</p>
                <h2><b>Subscription Data</b></h2>
                <p>You provide personal data to us as part of signing up for our newsletter on our websites. We may also collect personal information from you when you use interactive features of the Websites, promotions, requesting customer support, or otherwise communicating with us.</p>
                <h2><b>Contact Us Data</b></h2>
                <p>When you enquire about our products and services or request for demonstration of our product, we collect and store this data to communicate with you and respond to your enquiry. Our purpose in collecting information is to help us provide you with better service, such as notifications about special offers and promotions, or other relevant content delivered through targeted advertising.</p>
                <p>
                    The leadhawks.io or its affiliate's website may also collect a recipient's email address to help you to initiate and email the recipient you have selected. The recipient may contact us at info@herr-enterprises.com to request that we remove this information.</p>
                <Typography variant='h4' sx={{ color: "#03a4ed" }}> Cookies.</Typography>
                <p>We collect data through cookies</p>
                <p>Herr Enterprises uses cookies to help Herr Enterprises identify and track visitors, their usage of Herr Enterprises website, and their website access preferences. Herr Enterprises visitors can control cookies through your browser settings.</p>
                <p>For more details about how we use these technologies, please see our Cookie Policy How We Use the Information We Collect</p>
                <p>Customer Data will be used by Herr Enterprises in accordance with Customer's instructions, including any applicable terms in the Customer Agreement and as required by applicable law. Herr Enterprises is a processor of Customer Data and Customer is the controller.</p>
                <p>Herr Enterprises may use the information we obtain, license and collect about and from you for a number of business purposes, including for example, to: better tailor website and promotional content to visitor interests; verify your profile information; deliver targeted advertising; inform our partners of your business-related interests; improve the Service for internal business purposes; help our advertising partners better understand the audience they are reaching; and for purposes we disclose at the time you provide your Personal Information.
                </p>
                <Typography variant='h4' sx={{ color: "#03a4ed" }}> Lawful basis for processing.</Typography>
                <p>We have lawful basis to process your personal data. We also use your consent as basis for lawfully processing your personal data.</p>
                <p>We process your personal data only when we have a lawful basis. Presently, we use the Performance of Contract (i.e. to deliver the services to our customers) and consent as the lawful basis for processing. For certain processing, we may also use legitimate interests as provided under the Data Protection Regulations.
                </p>
                <p>In some cases, we may also have a legal obligation to collect personal information from you or may otherwise need the personal information to protect your vital interests or those of another person. Where you have consented to a particular processing, you have a right to withdraw the consent at any time.</p>
                <h2><b>Types of HR Data Collected</b></h2>
                <p>


                    Herr Enterprises collects certain Personal Data from its Employees and Job Applicants, including without limitation (collectively, the "HR Data").
                    name,
                    home address,
                    telephone number(s),
                    date of birth,
                    social security number or other government identification number,
                    salary,
                    bank account details,
                    job title,
                    employment contracts,
                    reviews and appraisals, competency assessments
                    business travel details
                    disciplinary records
                    IP address, system-generated logs
                    facts reported through the whistleblowing hotline or regular information and reporting channels,
                    evidence gathered in the course of the investigation, report of the investigation and outcome of the report


                </p>
                <Typography variant='h4' sx={{ color: "#03a4ed" }}>Purpose of Collection and Use of HR Data.</Typography>
                <p>Herr Enterprises processes HR Data relating to its Employees and Job Applicants in the US, UK or EEA for recruitment and HR management purposes at a global level, including:</p>
                <p>Carrying out and supporting Herr Enterprise's human resources functions and activities;</p>
                <p>Carrying out Herr Enterprise's obligations under employment contracts and employment and benefits laws;</p>
                <p>Managing workplace safety and health;</p>
                <p>Administering employee participation in benefits, compensation, human resources and training plans and programs;</p>
                <p>Managing employee performance;</p>
                <p>Implementing compliance and discipline procedures, and investigating and reporting on Employee compliance and discipline;</p>
                <p>Complying with Herr Enterprise's legal obligations and internal policies;</p>
                <p>Managing internal complaints or claims and litigation;</p>
                <p>Implementing and operating a whistle-blower hotline;</p>
                <p>Managing and conducting Herr Enterprise's business activities, including allocating company assets and human resources, project management, records management and compilation of audit trails or other reporting tools, managing mergers, acquisitions, sales, re-organizations or disposals and integration with purchaser;</p>
                <p>Operating IT and communication systems and monitoring Employee email and Internet usage to the extent permitted by applicable law.
                </p>
                <h2><b>Children</b></h2>
                <p>Herr Enterprises does not knowingly collect Personal or Usage Information from children under the age of 13 through https://Herr Enterprises.se, nor from any of our affiliates and partners. If you are under 13, please do not give us any Personal Information, and do not provide Personal Information to any website or web service without consulting your parent or guardian. If you have reason to believe that a child under the age of 13 has provided Personal Information to Herr Enterprises, please contact us, and we will seek to delete that information from our database.
                </p>
                <h2><b>Choice</b></h2>
                <p>Herr Enterprises is engaged in providing B2B services for customers to identify targets for the marketing of business products and in the process collects business contact data of companies and executives working in companies which are prospective customers for the products to be marketed.</p>
                <p>Herr Enterprises collect the data based on campaign information provided by Herr Enterprise's customers.</p>
                <Typography variant='h4' sx={{ color: "#03a4ed" }}>Advertising / Behavioural Targeting; How to Opt-Out</Typography>
                <p>When you opt out of the Service, Herr Enterprises will no longer use or share any of your Personal or anonymous Usage Information, unless you recently submitted Personal Information (within last 30 days) in order to access free content, in which case only the Content Provider associated with the content you recently acquired will have access to your information. Please contact Herr Enterprises at info@herr-enterprises.com to opt out of this option.</p>
                <h2><b>Cross-Border Data Transfers</b></h2>
                <p>Your data will be stored and processed in multiple countries including outside of the European Union (EU) Region. The Service and the servers and facilities that maintain the data we hold, are operated in the Sweden/India. Given that we are an international business, our use of your information necessarily involves the transmission of data on an international basis. If you are located in the European Union, Canada or elsewhere outside of the United States, please be aware that information we collect may be transferred to and processed in United States/India.
                </p>
                <h2><b>Accountability for onward transfer</b></h2>








            </Grid>
            <Grid item xs={1}></Grid>
        </Grid>
    );
};

export default Privacypolicy;